# Generated by Django 5.0 on 2024-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
