# Generated by Django 5.1 on 2024-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link_to_resume',
            field=models.URLField(blank=True, help_text='Provide a link to your resume.', null=True, verbose_name='Link to Resume'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume here.', null=True, upload_to='resumes/', verbose_name='Resume'),
        ),
    ]
