# Generated by Django 5.1 on 2024-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_issuingorganization_certification_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, help_text='Upload a picture of your project here.', null=True, upload_to='', verbose_name='Project Image'),
        ),
    ]
